syntax = "proto3";

package gameDataService;

import "common.proto";
import "google/protobuf/empty.proto";

option java_multiple_files = true;
option java_package = "com.dungeoncrawler.contracts.grpc.gamedata";

service GameDataService {
  rpc GetEntityTemplate(EntityTemplateGrpcRequest) returns (EntityTemplateGrpcResponse);
  rpc GetGameMap(GameMapRequest) returns (GameMapResponse);
  rpc GetPlayerClasses(google.protobuf.Empty) returns (common.PlayerClassListResponse);
}

message EntityTemplateGrpcRequest {
  string template_id = 1;
}

message EntityTemplateGrpcResponse {
  string template_id = 1;
  string name = 2;
  string type = 3;
  string description = 4;
  repeated string abilities = 5;
  common.Stats stats = 6;
}

message SpawnPointInfoMsg {
  common.HexMsg coordinate = 1;
  string templateId = 2;
}

message GameMapRequest {
  string level = 1;
}

message GameMapResponse {
  repeated common.TileMsg tiles = 1;
  repeated SpawnPointInfoMsg playerSpawnPoints = 2;
  repeated SpawnPointInfoMsg monsterSpawnPoints = 3;
}