version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dungeon-game-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: dungeon-game-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_WEBSOCKET_URL=http://backend:8080/gs-websocket
      - VITE_API_URL=http://backend:8080