version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rpg-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gamedata_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gamedata_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rpg-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: rpg-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: rpg-kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  # MICROSERVICES

  gamedata-service:
    container_name: gamedata-service
    build:
      context: .
      dockerfile: ./microservices/gamedata-service/Dockerfile
    ports:
      - "9092:9092" 
      - "9096:9096"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gamedata_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_GRPC_SERVER_PORT: 9096

  gamesession-service:
    container_name: gamesession-service
    build:
      context: .
      dockerfile: ./microservices/gamesession-service/Dockerfile
    ports:
      - "9091:9091"
      - "9095:9095"
    depends_on:
      - redis
      - kafka
      - gamedata-service
    environment:
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_GRPC_SERVER_PORT: 9095
      GRPC_CLIENTS_GAMEDATA_SERVICE_HOST: "gamedata-service"
      GRPC_CLIENTS_GAMEDATA_SERVICE_PORT: 9096

  websocket-service:
    container_name: websocket-service
    build:
      context: .
      dockerfile: ./microservices/websocket-service/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - gamesession-service
    environment:
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:29092
      GRPC_CLIENTS_GAMESESSION_SERVICE_HOST: "gamesession-service"
      GRPC_CLIENTS_GAMESESSION_SERVICE_PORT: 9095

  # FRONTEND
  
  frontend:
    container_name: rpg-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - websocket-service

volumes:
  postgres_data:
  redis_data: