spring:
  application:
    name: MyGame
game:
  settings:
    default-player-max-ap: 6
    default-monster-max-ap: 0
    move-cost-hv: 0.5
    move-cost-diag: 0.7
    default-attack-cost: 2
  map:
    generation:
      max-rooms: 15
      min-rooms: 3
      min-room-size: 6
      max-room-size: 10
      battleArenaRadius: 10
logging:
  level:
    org.springframework.messaging: TRACE
    org.springframework.web.socket: TRACE