spring:
  application:
    name: MyGame
game:
  settings:
    default-entity-max-ap: 8
    default-entity-current-ap: 6
    default-monster-max-ap: 0
    default-attack-cost: 2
    default-movement-cost: 1
    default-check-radius: 5
  map:
    generation:
      max-rooms: 15
      min-rooms: 3
      min-room-size: 6
      max-room-size: 10
      battleArenaRadius: 10
logging:
  level:
    org.springframework.messaging: TRACE
    org.springframework.web.socket: TRACE